version: '3.6'
services:
  do-sticky-floating-ip:
    build:
      context: ./docker/sticky-floating-ip/
      dockerfile: Dockerfile
    image: ivanmp91/do-sticky-floating-ip:${VERSION:-latest}

  opentodo-net:
    build:
      context: ./docker/opentodo-net/
      dockerfile: Dockerfile
    image: ivanmp91/opentodo-nginx-php
