stickyIP:
  image:
    name: ivanmp91/do-sticky-floating-ip
    tag: latest
    pullPolicy: Always
  scriptArgs:
    - "-u"
    - "/app/sticky-floating-ip.py"
    - "--ip=178.128.138.125"
    - "--tag=sticky-floating-ip"
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 1m
      memory: 5Mi