apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: opentodo
      tier: mysql
  serviceName: mysql
  replicas: {{ .Values.mysql.statefulset.replicaCount }}
  template:
    metadata:
      labels:
        app: opentodo
        tier: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.name }}:{{ .Values.mysql.image.tag }}"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: db_password
        ports:
        - containerPort: {{ .Values.mysql.service.port }}
          name: mysql
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
          subPath: mysql
      volumes:
      - name: mysql-vol
        persistentVolumeClaim:
          claimName: mysql-pv-claim