apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: opentodo
    tier: mysql
spec:
  storageClassName: {{ .Values.mysql.storage.className }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentodo-persistent-storage
  labels:
    app: opentodo
    tier: http
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi