apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentodo-persistent-storage
  labels:
    app: opentodo
    tier: http
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
